# Custom Language File for Launcher Customizer

[ejs.app]
title = "Requiem Launcher"

[ejs.landing]
mediaGitHubURL = "https://github.com/Aizen59200/Requiem---Decimation"
mediaXURL = "#"
mediaInstagramURL = "#"
mediaYouTubeURL = "#"
mediaDiscordURL = "https://discord.gg/pxd474NPNv"

[ejs.settings]
sourceGithubLink = "https://github.com/Aizen59200/Requiem---Decimation"
supportLink = "https://github.com/Aizen59200/Requiem---Decimation/issues"

[ejs.welcome]
welcomeHeader = "WELCOME TO Requiem - decimation"
welcomeDescription = "*"
welcomeDescCTA = "You are just a few clicks away from Requiem."
